# Travis configuration file
# Some configuration copied from Jekyll Continuous Integration Guide
# See https://jekyllrb.com/docs/continuous-integration/travis-ci/
language: ruby

# Should match version in Gemfile
rvm:
  - 3.3.6

install:
  - bundle install # Install needed gems
  - npm install -g sass-lint # Install Sass Lint (needed for ci.sh)

script: ./ci.sh # Run continuous integration shell script

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Cache gems
cache: bundler

sudo: false # route your build to the container-based infrastructure for a faster build
