# Travis configuration file
# Environment and script configuration copied from Jekyll Continuous Integration Guide (see https://jekyllrb.com/docs/continuous-integration/)
language: ruby
rvm:
  - 2.3.0

install: bundle install # Install needed gems
script: ci.sh # Run continuous integration shell script

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
