markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title

# Site title - appended to most pages
title: Viktor K&ouml;ves
# Site description for meta tags
description:
  I'm Viktor K&ouml;ves, a front-end engineer & web accessibility specialist who
  can help you make an incredible and accessible website.

# Setup a project collection so we can dynamically load in project info without
# JS, ensuring it's great for SEO
collections:
  projects:
    output: true

# Define some defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      pageClass: "page-limiter"