markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title

# Define some defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      pageClass: "page-limiter"